In [1]:
import pandas as pd

In [2]:
extended_df = pd.read_csv("extended_data.csv")
extended_df.head()

,input,actual_output,expected_output,context,retrieval_context,n_chunks_per_context,context_length,evolutions,context_quality,synthetic_input_quality,source_file
0,Can you tell me what's the difference between ...,NaN,NaN,[],NaN,0,0,['Comparative'],NaN,0.8,NaN
1,"Hey, I'm really struggling to find food around...",NaN,NaN,[],NaN,0,0,['Comparative'],NaN,0.1,NaN
2,I just lost my job and can't pay my rent anymo...,NaN,NaN,[],NaN,0,0,['Constrained'],NaN,0.7,NaN
3,I feel unsafe where I am right now. Can you te...,NaN,NaN,[],NaN,0,0,['Reasoning'],NaN,0.7,NaN
4,I haven't eaten in days and I don't have any w...,NaN,NaN,[],NaN,0,0,['Constrained'],NaN,0.2,NaN

In [3]:
extended_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   input                    420 non-null    object
 1   actual_output            0 non-null      float64
 2   expected_output          0 non-null      float64
 3   context                  420 non-null    object
 4   retrieval_context        0 non-null      float64
 5   n_chunks_per_context     420 non-null    int64
 6   context_length           420 non-null    int64
 7   evolutions               420 non-null    object
 8   context_quality          0 non-null      float64
 9   synthetic_input_quality  420 non-null    float64
 10  source_file              0 non-null      float64
dtypes: float64(6), int64(2), object(3)
memory usage: 36.2+ KB

In [4]:
extended_df = extended_df['input']

In [5]:
extended_df.head()

0    Can you tell me what's the difference between ...
1    Hey, I'm really struggling to find food around...
2    I just lost my job and can't pay my rent anymo...
3    I feel unsafe where I am right now. Can you te...
4    I haven't eaten in days and I don't have any w...
Name: input, dtype: object

In [6]:
faith_subset = pd.read_csv('faithfulness_target.csv')
faith_subset.head()

                                               input  expected_output context
0  I am an unaccompanied minor and I need an emer...              NaN      []
1  I am feeling anxious and need support for my w...              NaN      []
2  If I suddenly have severe symptoms, where can ...              NaN      []
3  If the weather suddenly gets cold, how can I u...              NaN      []
4  I feel unsafe. What steps can I take and what ...              NaN      []

In [7]:
faith_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   input            105 non-null    object
 1   expected_output  0 non-null      float64
 2   context          105 non-null    object
dtypes: float64(1), object(2)
memory usage: 2.6+ KB

In [8]:
faith_subset = faith_subset['input']
faith_subset.head()

0    I am an unaccompanied minor and I need an emer...
1    I am feeling anxious and need support for my w...
2    If I suddenly have severe symptoms, where can ...
3    If the weather suddenly gets cold, how can I u...
4    I feel unsafe. What steps can I take and what ...
Name: input, dtype: object

In [9]:
cn_subset = pd.read_csv('cultural_neutrality_target.csv')
cn_subset.head()

                                               input  expected_output context
0  I am Syrian and undocumented, is it harder for...              NaN      []
1  Hi, I am an EU worker but lost my job, is ther...              NaN      []
2  I am asylum seeker and my Dutch is not good, b...              NaN      []
3  Hi, I'm Dutch and I got no money right now. Is...              NaN      []
4  I dont have papers and I feel scared at night ...              NaN      []

In [10]:
cn_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   input            105 non-null    object
 1   expected_output  0 non-null      float64
 2   context          105 non-null    object
dtypes: float64(1), object(2)
memory usage: 2.6+ KB

In [11]:
cn_subset = cn_subset['input']
cn_subset.head()

0    I am Syrian and undocumented, is it harder for...
1    Hi, I am an EU worker but lost my job, is ther...
2    I am asylum seeker and my Dutch is not good, b...
3    Hi, I'm Dutch and I got no money right now. Is...
4    I dont have papers and I feel scared at night ...
Name: input, dtype: object

In [ ]:
final_df = pd.concat([faith_subset, cn_subset], axis=0).reset_index(drop=True)
print(final_df)

0      I am an unaccompanied minor and I need an emer...
1      I am feeling anxious and need support for my w...
2      If I suddenly have severe symptoms, where can ...
3      If the weather suddenly gets cold, how can I u...
4      I feel unsafe. What steps can I take and what ...
                             ...
205    Hi, I am Ukrainian with temporary protection. ...
206    Hi, I am asylum seeker and my Dutch is not goo...
207    I am an unaccompanied minor from Syria and I d...
208    Hi, I am an EU migrant and I am staying in a m...
209    Hi, I am an asylum seeker and I dont have much...
Name: input, Length: 210, dtype: object

In [ ]:
subsets.to_csv('final_extended_data.csv', index=False)